### Variables ###
@access=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMDAwMSIsImlhdCI6MTc0ODI2ODc3NiwiZXhwIjoxNzQ4MjcyMzc2fQ.w8B0TM45rdL2osdaDWkBJBnOEGGzP6JzQjMiAjwzKuQzYklZMma_Rbb1V9UUALRbyqr9BxKsOPTK4Y2DNn7E-A
@adminAccess=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc0MjQ4MTM5OSwiZXhwIjoxNzQyNDkyMTk5fQ.fgmYjGaGy3TsmnfFlsjsUQJot865RG-Dt8QW-5mE3nhm_W1Q5qLTPtS_BFXRKj4Ot_4K-wC6tBw77ULG4sb13Q
#####################################################################################################################

### USER and AUTH ###

### login (public & all users)
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "100011",
    "password": "passworD#1"
}

### login for admin
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "adminPassword"
}

### EMPLOYEE ###

### Fetch all employees info - Admin only
GET http://localhost:8080/api/employees HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access}}

### Fetch partial employees info - Admin only
GET http://localhost:8080/api/employees/partial/details HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access}}

### Fetch all employees with info for non-admin auth users
GET http://localhost:8080/api/employees/basic-info HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access}}



