### Variables
@access=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMDAwMSIsImlhdCI6MTc0MjQ4MTM2NCwiZXhwIjoxNzQyNDkyMTY0fQ.GY2IrP4Qj2bH4yyZcaRoYhZXPnT0RKRMt3aIh2FbCBw_CouiIK7a-EfjRiu03IE3H-1T9s_jNfo-AEoBwpS8lQ
@adminAccess=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc0MjQ4MTM5OSwiZXhwIjoxNzQyNDkyMTk5fQ.fgmYjGaGy3TsmnfFlsjsUQJot865RG-Dt8QW-5mE3nhm_W1Q5qLTPtS_BFXRKj4Ot_4K-wC6tBw77ULG4sb13Q
#####################################################################################################################

### login (public & all users)
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "10002",
    "password": "passworD#1"
}

### login for admin
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "adminPassword"
}